apiVersion: v1
kind: ConfigMap
metadata:
 name: app-config
 namespace: petclinic
data:
 SPRING_DATASOURCE_URL: jdbc:postgresql://db-service.petclinic.svc.cluster.local:5432/postgres
 SPRING_DATASOURCE_USERNAME: database

---

apiVersion: v1
kind: Secret
metadata:
 name: app-secret
 namespace: petclinic
type: Opaque
data:
 SPRING_DATASOURCE_PASSWORD: ZGF0YWJhc2UxMjM=

---

apiVersion: apps/v1
kind: Deployment
metadata:
 name: app-deployment
 namespace: petclinic
spec:
 replicas: 2
 selector:
  matchLabels:
   app: petclinic-app
 strategy:
  type: RollingUpdate
  rollingUpdate:
   maxUnavailable: 1
   maxSurge: 1
 template:
  metadata:
   labels:
    app: petclinic-app
  spec:
   containers:
    - name: petclinic-app
      image: darkosekulovski/petclinic:latest
      ports:
       - containerPort: 8080
      envFrom:
       - configMapRef:
          name: app-config
       - secretRef:
          name: app-secret
