apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: db-vc
 namespace: petclinic
 labels:
  app: postgres
spec:
 storageClassName: manual
 accessModes:
  - ReadWriteOnce
 resources:
  requests:
   storage: 1Gi
