apiVersion: v1
kind: PersistentVolume
metadata:
 name: db-volume
 namespace: petclinic
 labels:
  type: local
  app: postgres
spec:
 storageClassName: manual
 capacity:
  storage: 1Gi
 accessModes:
  - ReadWriteOnce
 hostPath:
  path: /data/postgresql
 persistentVolumeReclaimPolicy: Retain
